covid:
  outputs:
    dev:
      account: "qkecwgq-hq43255"
      database: "COVID"
      password: "dbtPassword123"
      role: "transform"
      schema: DEV
      threads: 1
      type: snowflake
      user: "dbt"
      warehouse: COMPUTE_WH
  target: dev